// SignUp Owner
POST http://localhost:5000/api/auth/SignUp HTTP/1.1
content-type: application/json

{
      "name": "Rohit Sikrewal",
      "contact_no": "",
      "gender": "",
      "email": "sikrw@gmail.com",
      "address": "",
      "password": "s",
      "persona": 0
}

###
// SignUp employee
POST http://localhost:5000/api/auth/SignUp HTTP/1.1
content-type: application/json

{
      "name": "Rohit Sikrewal",
      "contact_no": "4085496361",
      "gender": "Male",
      "email": "sikrewalrhgvghgho123@gmail.com",
      "address": "190 Ryland Street",
      "password": "xyz",
      "persona": 1
}

###
// SignUp Customer
POST http://localhost:5000/api/auth/SignUp HTTP/1.1
content-type: application/json

{
      "name": "Rohit Sikrewal",
      "contact_no": "4085496361",
      "gender": "Male",
      "email": "sa@gmail.com",
      "address": "190 Ryland Street",
      "password": "xyz",
      "persona": 2
}

###

// SignIp Owner
POST http://localhost:5000/api/auth/SignIn HTTP/1.1
content-type: application/json

{
      "email": "sikr13@gmail.com",
      "password": "ou",
      "persona": 0
}
###
// SignIp employee
POST http://localhost:5000/api/auth/SignIn HTTP/1.1
content-type: application/json

{
      "email": "sikrewavgsahgshgho123@gmail.com",
      "password": "z",
      "persona": 1
}
###
// SignIp customer
POST http://localhost:5000/api/auth/SignIn HTTP/1.1
content-type: application/json

{
      "email": "sart@gmail.com",
      "password": "yz",
      "persona": 2
}